services:
  django-app:
    build: 
      context: .
      dockerfile: Django.Dockerfile
    command: gunicorn manga_review.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/src
    expose: 
      - 8000
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:433
      - 8000:8000
    depends_on:
      - django-app
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs