# Generated by Django 5.1.1 on 2024-09-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0002_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("studio", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="animes_images/"
                    ),
                ),
                ("publication_year", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Activo", "Activo"),
                            ("Completado", "Completado"),
                            ("Hiatus", "Hiatus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("genres", models.ManyToManyField(to="mangas.genre")),
            ],
        ),
    ]
